development:
  adapter: postgresql
  encoding: unicode
  database: ninja_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ninja_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ninja_production
  pool: 5
